{
  "hash": "2b05435837355f788c44807126993928",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Evaluación Práctica Estadística\"\nsubtitle: \"Maestría en Aplicaciones de Información Espacial-Instituto Gulich\"\nauthor: \"Franco Barrionuevo\"\ndate: today\nformat:\n  pdf:\n    geometry:\n      - top=2.5cm\n      - bottom=2.5cm\n      - left=3cm\n      - right=2.5cm\n    number-sections: true\n\neditor_options:\n  chunk_output_type: inline\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Instalación y carga de librerías\nlibrary(dplyr)\n##install.packages(\"lawstat\")  \nlibrary(lawstat)\n##install.packages(\"GGally\")\n##install.packages(\"ggplot2\")\nlibrary(GGally)\n##install.packages(\"car\")\nlibrary(car)\n```\n:::\n\n\n## NDVI y efecto de la época del año\n\n#### Contexto\n\nSe dispone de una base de datos de mediciones del Índice de Vegetación de Diferencia Normalizada (NDVI) registradas en las cuatro estaciones del año 2020 en sitios de la región Pampeana con cobertura agrícola (*ndvi_4_estaciones.txt*). Cada observación corresponde a un sitio diferente y puede considerarse independiente. El objetivo es evaluar si el NDVI varía significativamente según la época del año.\n\n#### Exploración inicial\n\n1.  Cargue la base de datos e indique: ¿Cuántas observaciones tiene en total? ¿Cuántas observaciones hay por época? Presente el output de R que respalde su respuesta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Carga de los datos en una tabla  \ndata_ndvi <- read.table(\"datos/ndvi_4_estaciones.txt\")\n\n## Mostrar head de la tabla\nhead(data_ndvi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  estacion      ndvi\n1 invierno 0.3135280\n2 invierno 0.2442600\n3 invierno 0.1949603\n4 invierno 0.3098044\n5 invierno 0.2584004\n6 invierno 0.3417368\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Cuenta la cantidad de observaciones por estación\ntable(data_ndvi$estacion)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n invierno     otono primavera    verano \n       28        28        28        28 \n```\n\n\n:::\n:::\n\n\n**Respuesta:** Por cada estación hay un total de 28 observaciones del NDVI.\n\n---\n\n2.  Construya una tabla de estadística descriptiva que incluya, para cada época: n, media, desvío estándar, coeficiente de variación, mínimo y máximo. Presente la tabla en el informe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Tabla de estadística descriptiva\ndata_ndvi %>%\n  group_by(estacion) %>%\n  summarise(\n    n = n(),\n    media = mean(ndvi),\n    de = sd(ndvi),\n    cv = sd(ndvi) / mean(ndvi) * 100, \n    min = min(ndvi),\n    max = max(ndvi)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 7\n  estacion      n media     de    cv     min   max\n  <chr>     <int> <dbl>  <dbl> <dbl>   <dbl> <dbl>\n1 invierno     28 0.203 0.0905  44.5  0.0384 0.349\n2 otono        28 0.172 0.0918  53.3 -0.0473 0.317\n3 primavera    28 0.289 0.0786  27.2  0.129  0.439\n4 verano       28 0.608 0.103   17.0  0.385  0.900\n```\n\n\n:::\n:::\n\n\n---\n\n3.  Construya un gráfico de caja (*boxplot*) que permita comparar visualmente la distribución del NDVI entre épocas.\\\n    Incluya el gráfico en el informe y describa en 2–3 oraciones lo que observa: tendencias, variabilidad, presencia de valores atípicos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Graficar boxplot con librería por default\nboxplot(ndvi ~ estacion, data = data_ndvi,\n        xlab = \"Estación\", ylab = \"NDVI\")\n```\n\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Respuesta:** El gráfico de boxplot muestra que, a medida que se pasa del invierno al verano, los valores de la media de NDVI tienden a aumentar, lo cual se corrobora también en la tabla del ítem 3. Se observa además que la variabilidad entre las distintas estaciones es similar, siendo que el desvío estandar varía entre 0.07 y 0.10 según los resultados de la tabla del ítem 3. Finalmente, se identifica una observación atípica (*outlier*) correspondiente a la estación de verano.\n\n---\n\n#### Análisis principal\n\n4.  Análisis de comparación de medias. Indique con precisión: el estadístico de prueba, los grados de libertad y el p-valor. ¿Puede concluir que existe alguna diferencia de NDVI entre épocas (α = 0.05)?\n\nSe realizará un análisis de varianza (ANOVA) para comparar las medias de NDVI entre las distintas estaciones. Si bien el boxplot (ítem 3) sugiere que los valores de NDVI aumentan desde el invierno hacia el verano, es necesario evaluar si estas diferencias son estadísticamente significativas mediante la comparación formal de las medias.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Definir y ajustar el modelo para el test de ANOVA\nfit <- aov(ndvi ~ estacion, data = data_ndvi)\n\n## Mostrar un resumen del modelo ajustado\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nestacion      3  3.344  1.1147   133.2 <2e-16 ***\nResiduals   108  0.904  0.0084                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**Respuesta:**\n\n*Estadística de prueba*: En el test ANOVA, se corresponde al estadístico F que se computa como la relación entre el cuadrado medio del error entre tratamientos (CMTrat) y el cuadrado medio del error aleatorio (CMError). Para la prueba realizada para las mediciones del NDVI en las diferentes estaciones del año, \\\nF = 133.2.\n\n*Grados de libertad*: Los grados de libertad del tratamiento son 3 (k-1), mientras que los del error aleatorio 108 (N-k).\n\n*p-valor*: 2e-16\n\nA partir del p-valor obtenido, se puede concluir que para un nivel de significancia de 0.05 se puede rechazar la H0 (p-valor \\< 0.05). Para el caso en estudio, esto se traduce en que existe una diferencia significativa entre alguna de las medias $\\mu_i$ y $\\mu_{i'}$ tal que $i$ $\\neq$ $i'$ para las muestras de NDVI de las diferentes estaciones del año.\n\n---\n\n5.  Realice una comparación múltiple de medias. Pegue la tabla de resultados. ¿Qué épocas difieren significativamente entre sí?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Test de Tukey para diferencia entre medias \ntk <- TukeyHSD(fit)\ntk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = ndvi ~ estacion, data = data_ndvi)\n\n$estacion\n                          diff         lwr       upr     p adj\notono-invierno     -0.03117974 -0.09498108 0.0326216 0.5806052\nprimavera-invierno  0.08580799  0.02200665 0.1496093 0.0036165\nverano-invierno     0.40480202  0.34100068 0.4686034 0.0000000\nprimavera-otono     0.11698773  0.05318639 0.1807891 0.0000321\nverano-otono        0.43598176  0.37218042 0.4997831 0.0000000\nverano-primavera    0.31899404  0.25519270 0.3827954 0.0000000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cambio de los labels comparación de estaciones\nrownames(tk$estacion) <- c(\n  \"O-I\",\n  \"P-I\",\n  \"V-I\",\n  \"P-O\",\n  \"V-O\",\n  \"V-P\"\n)\n\n## Plot de los resultados del test de Tukey\nplot(tk)\n```\n\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Respuesta:**\n\nSe realizó una comparación múltiple de las medias del NDVI para las diferentes estaciones a través del test de Tukey. Dicho test propone como hipótesis H0: $\\mu_i$ $=$ $\\mu_{i'}$ y como Ha: $\\mu_i$ $\\neq$ $\\mu_{i'}$ tal que $i$ $\\neq$ $i'$.\n\nEl resultado del test muestra que no se rechaza la hipótesis H0 a un nivel 0.05 para la comparación entre las medias de otoño e invierno (O-I), con un p-valor igual a 0.5806 (es decir p-valor \\> 0.05). Para el resto de las comparaciones, los resultados son estadísticamente significativos para rechazar H0 a nivel 0.05.\n\nLa comparación de medias a través del test de Tukey junto a su gráfico asociado, permiten además concluir la primera impresión obtenida sobre los datos. A medida que se pasa del otoño al verano, la media del NDVI aumenta. Esto se puede expresa de la siguiente forma $\\mu_{Inv}$ $=$ $\\mu_{Oto}$ $<$ $\\mu_{Pri}$ $<$ $\\mu_{Ver}$\n\n---\n\n6.  Enumere y verifique si se cumplen los supuestos del modelo.\n\n**Respuesta:**\n\nLos supuestos del modelo de ANOVA consideran que el término de error aleatorio del modelo ($\\epsilon_{ij}$) cumple cumple con los siguientes criterios\n\na\\) *Independencia*: Se garantiza a través de un proceso de aleatorización del proceso de muestreo.\n\nb\\) *Normalidad*\n\nc\\) *Homogeneindad de varianzas*\n\n[Evaluación de la normalidad]{.underline}\n\nLa normalidad del término de error aleatorio se evaluó a través de un gráfico de Q-Q plot de los residuos y el test de Shapiro-Wilk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Ploteo QQplot para evaluar normalidad de los residuos\nqqnorm(rstandard(fit))\nqqline(rstandard(fit))\n```\n\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Test de Shapiro-Wilk para evaluar normalidad de los residuos\nshapiro.test(rstandard(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  rstandard(fit)\nW = 0.99132, p-value = 0.7025\n```\n\n\n:::\n:::\n\n\nEl gráfico de Q-Q plot muestra que los puntos, correspondientes a los residuos, se ordenan alrededor de la recta identidad (quantil muestral = quantil teórico). Esto aporta evidencia de que los residuos siguen aproximadamente una distribución normal.\n\nEl test de Shapiro-Wilks plantea como H0 ​que los residuos siguen una distribución normal, mientras que la Ha ​plantea que no la siguen. El resultado del test muestra que, a un nivel de significancia de 0.05, no se rechaza H0, con un p-valor de 0.7025 (es decir, p-valor \\> 0.05). De esta manera, no existe evidencia estadísticamente significativa para afirmar que los residuos no siguen una distribución normal.\n\n[Homogeneidad de varianzas]{.underline}\n\nLa homogeneidad de varianzas del término de error aleatorio se evaluó a través de un gráfico de residuos estandarizados versus valores predichos y el test de Levene.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-11-1.pdf)\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Test de Levene para evaluación de homogeneidad de varianzas\ncar::leveneTest(data_ndvi$ndvi, data_ndvi$estacion, center = mean)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in leveneTest.default(data_ndvi$ndvi, data_ndvi$estacion, center =\nmean): data_ndvi$estacion coerced to factor.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = mean)\n       Df F value Pr(>F)\ngroup   3  0.5698 0.6361\n      108               \n```\n\n\n:::\n:::\n\n\nEl gráfico de residuos estandarizados versus valores predichos muestra que los residuos presentan una dispersión similar alrededor de 0, sin detectarse patrones observables. Esto aporta evidencia de homogeneidad de varianzas.\n\nEl test de Levene plantea como H0 ​la igualdad de varianzas entre grupos, mientras que la Ha plantea que al menos una varianza difiere. El resultado del test muestra que, a un nivel de significancia de 0.05, no se rechaza H0, con un p-valor de 0.6361 (es decir, p-valor \\> 0.05). De esta manera, no existe evidencia estadísticamente significativa para afirmar que las varianzas difieren entre grupos.\n\n---\n\n#### Interpretación y juicio crítico\n\n7.  El p-valor del análisis principal resultó menor a 0.001. ¿Significa esto que todas las épocas son diferentes entre sí? Responda usando los resultados concretos de la comparación múltiple.\n\n**Respuesta:**\n\nEl resultado obtenido permite rechazar la H0 del test ANOVA (p-valor = 2e-16), la cual plantea la igualdad de medias entre los k grupos, a un nivel de significancia de 0.001 (p-valor \\< 0.001). Sin embargo, esto no permite afirmar que todas las medias de NDVI para las diferentes estaciones difieran entre sí. Para identificar específicamente qué medias presentan diferencias significativas, se realizó un test de comparación múltiple de medias. En este caso, se empleó el test de Tukey (ítem 5). Los resultados obtenidos muestran que, para un nivel de significancia de 0.05, las únicas medias que no difieren significativamente entre sí son las correspondientes a invierno ($\\mu_{Inv}$ ) y otoño ($\\mu_{Oto}$), mientras que el resto de las comparaciones presentan diferencias significativas.\n\n---\n\n8.  Su colega decidió no verificar los supuestos del modelo. En su caso particular, ¿qué consecuencias podría tener esa decisión? Use los resultados que obtuvo anteriormente para fundamentar.\n\n**Respuesta:**\n\nPara el caso en particular analizado en este trabajo, no haber verificado los supuesto del modelo de ANOVA, no hubiera tenido consecuencias afecten las conclusiones. En un caso donde los supuestos no se cumplieran, y se empleara dicho test, los resultados podrían ser erroneos ya que el estádistico a evaluar debería ser uno diferente, por ejemplo.\n\n---\n\n---\n\n## Regresión lineal simple y múltiple: evaporación de suelo\n\n#### Contexto\n\nLa base de datos (*evaporacion.txt*) contiene registros diarios de evaporación de suelo (agua_eva, en mm), temperatura máxima del suelo (tpsuelma, en °F) y temperatura máxima del aire (tairemax, en °F). El objetivo es construir un modelo estadístico para predecir la evaporación diaria.\n\n#### Exploración y correlación\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Carga de los datos\ndata_evap <- read.table(\"datos/evaporacion.txt\", head = TRUE)\n\n## Mostrar head de la tabla\nhead(data_evap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tpsuelma tairemax agua_eva\n1       84       85       30\n2       84       86       34\n3       79       83       33\n4       81       83       26\n5       84       88       41\n6       74       77        4\n```\n\n\n:::\n:::\n\n\n1.  Cargue los datos y construya una matriz de dispersión (*scatterplot matrix*) que muestre las relaciones entre las tres variables. Incluya el gráfico. Describa en pocas líneas: ¿qué relaciones observa? ¿Parecen lineales?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Visualización de la scatterplot matrix\npairs(data_evap)\n```\n\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Respuesta:**\n\nLos scatter plot muestran, a primera vista, que para todas las combinaciones entre variables hay una relación lineal. La misma debe posteriormente probarse a través de la evaluación de parámetros estadísticos.\n\n---\n\n2.  Calcule la matriz de correlaciones entre las tres variables. Pegue el output. Preste especial atención a la correlación entre tpsuelma y tairemax: ¿cuánto vale y qué implicancia puede tener esto al construir un modelo de regresión múltiple?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Visualización de la matriz de correlación\ncor(data_evap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          tpsuelma  tairemax  agua_eva\ntpsuelma 1.0000000 0.9268580 0.8933048\ntairemax 0.9268580 1.0000000 0.8509974\nagua_eva 0.8933048 0.8509974 1.0000000\n```\n\n\n:::\n:::\n\n\n**Respuesta:**\n\nEl coeficiente de correlación entre tpsuelma y tairemax (r = 0.9268) muestra un alto grado de relación lineal entre las variables. Construir un modelo que incluya ambas variables, puede dar como un resultado uno donde no sea distinguible el efecto individual de cada una sobre la variable dependiente.\n\n---\n\n#### Modelo de regresión múltiple\n\n3.  Ajuste un modelo de regresión lineal múltiple con agua_eva como variable respuesta, y tpsuelma y tairemax como regresoras. Pegue el summary() completo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Defino un primer modelo\n## Variables predictoras: T. máxima del suelo (tpsuelma) y T. máxima del aire (tairemax)\nmodel_1 <- lm(agua_eva ~ tpsuelma + tairemax, data = data_evap)\n\n## Summary del modelo\nsummary(model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = agua_eva ~ tpsuelma + tairemax, data = data_evap)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.4001  -2.1488   0.0814   3.3825  13.2875 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -169.4393    24.7330  -6.851    7e-07 ***\ntpsuelma       1.8969     0.6466   2.934  0.00768 ** \ntairemax       0.4734     0.7325   0.646  0.52479    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.549 on 22 degrees of freedom\nMultiple R-squared:  0.8018,\tAdjusted R-squared:  0.7837 \nF-statistic: 44.49 on 2 and 22 DF,  p-value: 1.859e-08\n```\n\n\n:::\n:::\n\n\n---\n\n4.  Indique el valor del $R^{2}$ ajustado obtenido. ¿Qué significa concretamente en el contexto de este problema? Escriba una oración que un profesional sin formación en estadística avanzada pueda entender.\n\n**Respuesta:**\n\nEl valor de $R^{2}$ ajustado obtenido para el modelo ajustado fue de 0.7837. Este parámetro permite medir la proporción de variabilidad de la variable respuesta que es explicada por el modelo ajustado respecto de la variabilidad total observada. En el contexto del problema en estudio, esto puede interpretarse como que aproximadamente el 78% de las variaciones observadas en la evaporación del suelo pueden ser explicadas a partir del cambio en la temperatura del suelo y la temperatura del aire mediante el modelo ajustado.\n\n---\n\n5.  Utilizando los coeficientes estimados del modelo múltiple (ítem 3): ¿Qué se espera que ocurra con la evaporación si la temperatura máxima del suelo aumenta 1°F, manteniendo constante la temperatura del aire? Use el valor exacto del coeficiente de su output para responder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Mostrar los coeficientes del modelo ajustado \ncoefficients(model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)     tpsuelma     tairemax \n-169.4392837    1.8969411    0.4734152 \n```\n\n\n:::\n:::\n\n\n**Respuesta:**\n\nEl coeficiente del modelo ajustado para la temperatura máxima del suelo obtenido fue $\\beta_{tpsuelma}$ = 1.8969 mm/°F. Si se mantiene la temperatura máxima del aire constante, un cambio en 1 °F de la tempratura del suelo, se va a traducir en el aumento de aproximadamente 1.90 mm en la evapotranspiración.\n\n---\n\n6.  Calcule el Factor de Inflación de la Varianza (VIF) para las variables del modelo múltiple. Pegue el output. ¿Hay indicios de multicolinealidad? ¿Qué valor o criterio utilizó para tomar esa decisión?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Cálculo del factor VIF\ncar::vif(model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntpsuelma tairemax \n7.095507 7.095507 \n```\n\n\n:::\n:::\n\n\n**Respuesta:**\n\nEl valor VIF para ambas variables resultó ser \\> 5. Esto muestra tanto la temperatura del suelo como la del aire medidas presentan multicolinealidad.\n\n---\n\n7.  Ajuste dos modelos de regresión lineal simple: uno con *tpsuelma* como regresora y otro con *tairemax*. Para cada modelo indique el $R^{2}$ y compárelo con el $R^{2}$ ajustado del modelo múltiple del ítem 3. Organice los resultados en una tabla comparativa.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Defino modelo 2.\n## Variable predictora: T. máxima del suelo (tpsuelma)\nmodel_2 <- lm(agua_eva ~ tpsuelma, data = data_evap)\n\n## Defino modelo 3\n## Variable predictora: T. máxima del aire (tairemax)\nmodel_3 <- lm(agua_eva ~ tairemax, data = data_evap)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Summary modelo 2\nsummary(model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = agua_eva ~ tpsuelma, data = data_evap)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.6100  -2.4627   0.5269   2.5373  12.9585 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -160.4133    20.1522  -7.960 4.67e-08 ***\ntpsuelma       2.2842     0.2396   9.532 1.87e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.465 on 23 degrees of freedom\nMultiple R-squared:  0.798,\tAdjusted R-squared:  0.7892 \nF-statistic: 90.86 on 1 and 23 DF,  p-value: 1.874e-09\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Summary modelo 3\nsummary(model_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = agua_eva ~ tairemax, data = data_evap)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-18.5049  -3.4357  -0.5049   5.4258  13.3565 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -184.9817    27.8693  -6.637 9.01e-07 ***\ntairemax       2.4654     0.3172   7.771 7.03e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.554 on 23 degrees of freedom\nMultiple R-squared:  0.7242,\tAdjusted R-squared:  0.7122 \nF-statistic: 60.39 on 1 and 23 DF,  p-value: 7.03e-08\n```\n\n\n:::\n:::\n\n\n**Respuesta:**\n\nEn la tabla de continuación de resumen los resultados del $R^{2}$ ajustado para los tres modelos\n\n| Modelo     | Var. predictora              | $R^{2}$ (Ajustado) |\n|------------|------------------------------|--------------------|\n| *Modelo 1* | T. Máx. Suelo + T. Máx. Aire | 0.7837             |\n| *Modelo 2* | T. Máx. Suelo                | 0.7892             |\n| *Modelo 3* | T. Máx. Aire                 | 0.7122             |\n\n---\n\n8.  Considerando los resultados de los ítems 2, 3, 6 y 7 (correlación entre predictores, coeficientes estimados, multicolinealidad y bondad de ajuste): ¿cuál de los tres modelos recomendaría para predecir la evaporación? Justifique explícitamente su elección.\n\n**Respuesta:**\n\nEl análisis de correlación entre predictores arroja El resultado de los $R^{2}$ ajustados para los tres modelos arroja que el que utiliza la variable de temperatura máxima del suelo (*tpsuelma*), es la que tiene el coeficiente más alto. De esta forma, es el que mejor explica la variación del cambio de la evaporación del suelo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## \nplot(data_evap$tpsuelma, data_evap$agua_eva, \n     xlab = \"T. Máx. Suelo (°F)\", \n     ylab = \"Evaporación agua (mm)\")\n\nabline(coefficients(model_2), col = \"red\", lwd = 2)\n\nlegend(\"topleft\", \n       legend = \"Modelo 2\", \n       col = \"red\", \n       lwd = 2,\n       bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\n\n9.  Se registró un día con *tpsuelma* = 88°F y *tairemax* = 90°F. Usando los coeficientes del modelo que seleccionó en el ítem 8, prediga la evaporación esperada ese día. Muestre el cálculo explícito con los valores numéricos de su ecuación ajustada (no alcanza con pegar la salida de predict(); escriba la operación aritmética)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Guardo los beta del modelo ajustado\nbeta_0 <- coefficients(model_2)[1] ## beta_0 = -160.4133 \nbeta_1 <- coefficients(model_2)[2] ## beta_1 = 2.284238 \n\n## Defino tpsuelma\nx_pred <- 88 ## tpsuelma = 88°F\n\n## Predicción\ny_pred <- beta_0 + beta_1*x_pred\ny_pred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n   40.59969 \n```\n\n\n:::\n:::\n\n\n**Respuesta:**\n\nEl valor predicho para una temperatura de 88 °F fue de 40.6 mm.\n\n---\n\n#### Diagnóstico del modelo\n\n10. Para el modelo seleccionado, incluya:\n\n<!-- -->\n\na)  El gráfico de residuos vs. valores ajustados.\nb)  Una evaluación escrita: ¿se observa algún patrón sistemático en los residuos? ¿Considera que el supuesto de homocedasticidad se cumple? Fundamente su respuesta en funcion de lo que muestra el gráfico.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Ploteo gráfico de residuos estandarizados vs. valores ajustados\nplot(fitted.values(model_2), rstandard(model_2),\n     xlab = \"Valores ajustados\", ylab = \"Residuos estandarizados\")\n```\n\n::: {.cell-output-display}\n![](TrabajoFinalEstd-Barrionuevo_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Respuesta:**\n\nA partir del gráfico de residuos estandarizados vs. valores ajustados, no se observa que los residuos sigan un patrón definido. Es decir, a lo largo del eje de valores predichos, los residuos se distribuyen de manera aproximadamente homogénea alrededor de 0, principalmente entre -2 y 2. En función de esto, es posible decir que se cumple el supuesto de homocedasticidad.\n\n---\n\n11. Un estudiante observa que el modelo múltiple (ítem 3) tiene un $R^{2}$ mayor que cualquiera de los dos modelos simples, y concluye que “siempre es mejor incluir más variables porque el $R^{2}$ solo puede aumentar o mantenerse igual”. ¿Está de acuerdo con esta afirmación? Desarrolle su respuesta considerando al menos dos argumentos estadísticos concretos.\n\nNo es correcto afirmar que, al incluir más variables predictoras en el ajuste de un modelo, el $R^{2}$ ajustado necesariamente aumenta o se mantiene constante. Esto es lo que se observó para el caso del modelo ajustado para la evaporación del agua en función de las temperaturas del suelo y del aire. En este caso, al incluir ambas variables predictoras, la bondad de ajuste del modelo resulta menor que al incluir solo una de ellas. Esto se debe a que agregar información redundante, producto de la alta multicolinealidad entre las variables predictoras, incrementa la complejidad del modelo sin mejorar su capacidad explicativa.\n",
    "supporting": [
      "TrabajoFinalEstd-Barrionuevo_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}