<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Franco Barrionuevo">

<title>Evaluación Práctica</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="TrabajoFinalEstd-Barrionuevo_files/libs/clipboard/clipboard.min.js"></script>
<script src="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/popper.min.js"></script>
<script src="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/anchor.min.js"></script>
<link href="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TrabajoFinalEstd-Barrionuevo_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TrabajoFinalEstd-Barrionuevo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TrabajoFinalEstd-Barrionuevo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TrabajoFinalEstd-Barrionuevo_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Evaluación Práctica</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Franco Barrionuevo </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Instalación y carga de librerías</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">##install.packages("lawstat")  </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lawstat)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="do">##install.packages("GGally")</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="do">##install.packages("ggplot2")</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: ggplot2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">##install.packages("car")</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:lawstat':

    levene.test</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
</div>
<section id="ndvi-y-efecto-de-la-época-del-año" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="ndvi-y-efecto-de-la-época-del-año"><span class="header-section-number">1</span> NDVI y efecto de la época del año</h2>
<section id="contexto" class="level4" data-number="1.0.1">
<h4 data-number="1.0.1" class="anchored" data-anchor-id="contexto"><span class="header-section-number">1.0.1</span> Contexto</h4>
<p>Se dispone de una base de datos de mediciones del Índice de Vegetación de Diferencia Normalizada (NDVI) registradas en las cuatro estaciones del año 2020 en sitios de la región Pampeana con cobertura agrícola (<em>ndvi_4_estaciones.txt</em>). Cada observación corresponde a un sitio diferente y puede considerarse independiente. El objetivo es evaluar si el NDVI varía significativamente según la época del año.</p>
</section>
<section id="exploración-inicial" class="level4" data-number="1.0.2">
<h4 data-number="1.0.2" class="anchored" data-anchor-id="exploración-inicial"><span class="header-section-number">1.0.2</span> Exploración inicial</h4>
<ol type="1">
<li>Cargue la base de datos e indique: ¿Cuántas observaciones tiene en total? ¿Cuántas observaciones hay por época? Presente el output de R que respalde su respuesta.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Carga de los datos en una tabla  </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data_ndvi <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"datos/ndvi_4_estaciones.txt"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Mostrar head de la tabla</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_ndvi)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  estacion      ndvi
1 invierno 0.3135280
2 invierno 0.2442600
3 invierno 0.1949603
4 invierno 0.3098044
5 invierno 0.2584004
6 invierno 0.3417368</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Cuenta la cantidad de observaciones por estación</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_ndvi<span class="sc">$</span>estacion)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 invierno     otono primavera    verano 
       28        28        28        28 </code></pre>
</div>
</div>
<p><strong>Respuesta:</strong> Por cada estación hay un total de 28 observaciones del NDVI.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="2" type="1">
<li>Construya una tabla de estadística descriptiva que incluya, para cada época: n, media, desvío estándar, coeficiente de variación, mínimo y máximo. Presente la tabla en el informe.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Tabla de estadística descriptiva</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>data_ndvi <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(estacion) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(ndvi),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">de =</span> <span class="fu">sd</span>(ndvi),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">cv =</span> <span class="fu">sd</span>(ndvi) <span class="sc">/</span> <span class="fu">mean</span>(ndvi) <span class="sc">*</span> <span class="dv">100</span>, </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(ndvi),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(ndvi)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  estacion      n media     de    cv     min   max
  &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 invierno     28 0.203 0.0905  44.5  0.0384 0.349
2 otono        28 0.172 0.0918  53.3 -0.0473 0.317
3 primavera    28 0.289 0.0786  27.2  0.129  0.439
4 verano       28 0.608 0.103   17.0  0.385  0.900</code></pre>
</div>
</div>
<p>________________________________________________________________________________________________________________</p>
<ol start="3" type="1">
<li>Construya un gráfico de caja (<em>boxplot</em>) que permita comparar visualmente la distribución del NDVI entre épocas.<br>
Incluya el gráfico en el informe y describa en 2–3 oraciones lo que observa: tendencias, variabilidad, presencia de valores atípicos.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Graficar boxplot con librería por default</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(ndvi <span class="sc">~</span> estacion, <span class="at">data =</span> data_ndvi,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Estación"</span>, <span class="at">ylab =</span> <span class="st">"NDVI"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Respuesta:</strong> El gráfico de boxplot muestra que, a medida que se pasa del invierno al verano, los valores de NDVI tienden a aumentar. Se observa además que la variabilidad entre las distintas estaciones es similar, lo cual se corrobora en la tabla del punto 3, donde el desvío estándar varía entre 0.07 y 0.10. Finalmente, se identifica una observación atípica (<em>outlier</em>) correspondiente a la estación de verano.</p>
<p>________________________________________________________________________________________________________________</p>
</section>
<section id="análisis-principal" class="level4" data-number="1.0.3">
<h4 data-number="1.0.3" class="anchored" data-anchor-id="análisis-principal"><span class="header-section-number">1.0.3</span> Análisis principal</h4>
<ol start="4" type="1">
<li>Análisis de comparaciónd de medias. Indique con precisión: el estadístico de prueba, los grados de libertad y el p-valor. ¿Puede concluir que existe alguna diferencia de NDVI entre épocas (α = 0.05)?</li>
</ol>
<p>Se realizará un análisis de varianza (ANOVA) para comparar las medias de NDVI entre las distintas estaciones. Si bien el boxplot (punto 3) sugiere que los valores de NDVI aumentan desde el invierno hacia el verano, es necesario evaluar si estas diferencias son estadísticamente significativas mediante la comparación formal de las medias.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Definir y ajustar el modelo para el test de ANOVA</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">aov</span>(ndvi <span class="sc">~</span> estacion, <span class="at">data =</span> data_ndvi)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Mostrar un resumen del modelo ajustado</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
estacion      3  3.344  1.1147   133.2 &lt;2e-16 ***
Residuals   108  0.904  0.0084                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p><em>Estadística de prueba</em>: En el test ANOVA, se corresponde al estadístico F que se computa como la relación entre el cuadrado medio del error entre tratamientos (CMTrat) y el cuadrado medio del error aleatorio (CMError). Para la prueba realizada entre las estaciones, F = 133.2.</p>
<p><em>Grados de libertad</em>: Los grados de libertad del tratamiento son 3 (k-1), mientras que los del error aleatorio 108 (N-k).</p>
<p><em>p-valor</em>: 2e-16</p>
<p>A partir del p-valor obtenido, se puede concluir que para un nivel de significancia de 0.05 se puede rechazar la H0 (p-valor &lt; 0.05). Para el caso en estudio, esto se traduce en que existe una diferencia significativa entre alguna de las medias <span class="math inline">\(\mu_i\)</span> y <span class="math inline">\(\mu_{i'}\)</span> tal que <span class="math inline">\(i\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(i'\)</span> para las muestras de NDVI de las diferentes estaciones del año.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="5" type="1">
<li>Realice una comparación múltiple de medias. Pegue la tabla de resultados. ¿Qué épocas difieren significativamente entre sí?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test de Tukey para diferencia entre medias </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>tk <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(fit)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>tk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = ndvi ~ estacion, data = data_ndvi)

$estacion
                          diff         lwr       upr     p adj
otono-invierno     -0.03117974 -0.09498108 0.0326216 0.5806052
primavera-invierno  0.08580799  0.02200665 0.1496093 0.0036165
verano-invierno     0.40480202  0.34100068 0.4686034 0.0000000
primavera-otono     0.11698773  0.05318639 0.1807891 0.0000321
verano-otono        0.43598176  0.37218042 0.4997831 0.0000000
verano-primavera    0.31899404  0.25519270 0.3827954 0.0000000</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cambio de los labels comparación de estaciones</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(tk<span class="sc">$</span>estacion) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"O-I"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"P-I"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V-I"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"P-O"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V-O"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V-P"</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Plot de los resultados del test de Tukey</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>Se realizó una comparación múltiple de las medias del NDVI para las diferentes estaciones a través del test de Tukey. Dicho test propone como hipótesis H0: <span class="math inline">\(\mu_i\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(\mu_{i'}\)</span> y como Ha: <span class="math inline">\(\mu_i\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(\mu_{i'}\)</span> tal que <span class="math inline">\(i\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(i'\)</span>.</p>
<p>El resultado del test muestra que se rechaza la hipótesis H0 a un nivel 0.05 para la comparación entre las medias de otoño e invierno, con un p-valor igual a 0.5806 (es decir p-valor &gt; 0.05). Para el resto de las comparaciones, no se rechaza H0 a nivel 0.05.</p>
<p>La comparación de medias a través del test de Tukey junto a su gráfico asociado, permiten además concluir la primera impresión obtenida sobre los datos. A medida que se pasa del otoño al verano, la media del NDVI aumenta. Esto se puede expresa de la siguiente forma <span class="math inline">\(\mu_{Inv}\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(\mu_{Oto}\)</span> <span class="math inline">\(&lt;\)</span> <span class="math inline">\(\mu_{Pri}\)</span> <span class="math inline">\(&lt;\)</span> <span class="math inline">\(\mu_{Ver}\)</span></p>
<p>________________________________________________________________________________________________________________</p>
<ol start="6" type="1">
<li>Enumere y verifique si se cumplen los supuestos del modelo.</li>
</ol>
<p><strong>Respuesta:</strong></p>
<p>Los supuestos del modelo de ANOVA son:</p>
<p>a) <em>Independencia</em>: Se garantiza a través de un proceso de aleatorización del proceso de muestreo.</p>
<p>b) <em>Normalidad</em>: El término de error aleatorio para las n observaciones de las k poblaciones tienen distribución normal.</p>
<p>c) <em>Homogeneindad de varianzas:</em> El término de error aleatorio para las n observaciones de las k poblaciones son iguales.</p>
<p><u>Evaluación de la normalidad</u></p>
<p>La normalidad del término de error aleatorio se evaluó a través de un gráfico de Q-Q plot de los residuos y el test de Shapiro-Wilk.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Ploteo QQplot para evaluar normalidad de los residuos</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">rstandard</span>(fit))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">rstandard</span>(fit))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test de Shapiro-Wilk para evaluar normalidad de los residuos</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">rstandard</span>(fit))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  rstandard(fit)
W = 0.99132, p-value = 0.7025</code></pre>
</div>
</div>
<p>El gráfico de Q-Q plot muestra que los puntos, correspondientes a los residuos, se ordenan alrededor de la recta identidad (quantil muestral = quantil teórico). Esto aporta evidencia de que los residuos siguen aproximadamente una distribución normal.</p>
<p>El test de Shapiro-Wilks plantea como H0 ​que los residuos siguen una distribución normal, mientras que la Ha ​plantea que no la siguen. El resultado del test muestra que, a un nivel de significancia de 0.05, no se rechaza H0, con un p-valor de 0.7025 (es decir, p-valor &gt; 0.05). De esta manera, no existe evidencia estadísticamente significativa para afirmar que los residuos no siguen una distribución normal.</p>
<p><u>Homogeneidad de varianzas</u></p>
<p>La homogeneidad de varianzas del término de error aleatorio se evaluó a través de un gráfico de residuos estandarizados versus valores predichos y el test de Levene.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Ploteo de gráfico de residuos estandarizados vs valores predichos para evaluar</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="do">## homogeneidad de varianzas</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted.values</span>(fit), <span class="fu">rstandard</span>(fit),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Valores predichos"</span>, <span class="at">ylab =</span> <span class="st">"Residuos estandarizados"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test de Levene para evaluación de homogeneidad de varianzas</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(data_ndvi<span class="sc">$</span>ndvi, data_ndvi<span class="sc">$</span>estacion, <span class="at">center =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in leveneTest.default(data_ndvi$ndvi, data_ndvi$estacion, center =
mean): data_ndvi$estacion coerced to factor.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
       Df F value Pr(&gt;F)
group   3  0.5698 0.6361
      108               </code></pre>
</div>
</div>
<p>El gráfico de residuos estandarizados versus valores predichos muestra que los residuos presentan una dispersión similar alrededor de 0, sin detectarse patrones observables. Esto aporta evidencia de homogeneidad de varianzas.</p>
<p>El test de Levene plantea como H0 ​la igualdad de varianzas entre grupos, mientras que la Ha plantea que al menos una varianza difiere. El resultado del test muestra que, a un nivel de significancia de 0.05, no se rechaza H0, con un p-valor de 0.6361 (es decir, p-valor &gt; 0.05). De esta manera, no existe evidencia estadísticamente significativa para afirmar que las varianzas difieren entre grupos.</p>
<p>________________________________________________________________________________________________________________</p>
</section>
<section id="interpretación-y-juicio-crítico" class="level4" data-number="1.0.4">
<h4 data-number="1.0.4" class="anchored" data-anchor-id="interpretación-y-juicio-crítico"><span class="header-section-number">1.0.4</span> Interpretación y juicio crítico</h4>
<ol start="7" type="1">
<li>El p-valor del análisis principal resultó menor a 0.001. ¿Significa esto que todas las épocas son diferentes entre sí? Responda usando los resultados concretos de la comparación múltiple.</li>
</ol>
<p><strong>Respuesta:</strong></p>
<p>El resultado obtenido (p-valor &lt; 0.001) permite rechazar la H0 del test ANOVA, la cual plantea la igualdad de medias entre los k grupos, a un nivel de significancia de 0.001. Sin embargo, esto no permite afirmar que todas las medias de NDVI para las diferentes estaciones difieran entre sí. Para identificar específicamente qué medias presentan diferencias significativas, se realizó un test de comparación múltiple de medias. En este caso, se empleó el test de Tukey (ítem 5). Los resultados obtenidos muestran que, para un nivel de significancia de 0.05, las únicas medias que no difieren significativamente entre sí son las correspondientes a invierno (<span class="math inline">\(\mu_{Inv}\)</span> ) y otoño (<span class="math inline">\(\mu_{Oto}\)</span>), mientras que el resto de las comparaciones presentan diferencias significativas.</p>
<ol start="8" type="1">
<li>Su colega decidió no verificar los supuestos del modelo. En su caso particular, ¿qué consecuencias podría tener esa decisión? Use los resultados que obtuvo anteriormente para fundamentar.</li>
</ol>
<p><strong>Respuesta:</strong></p>
<p>El resul</p>
<p>________________________________________________________________________________________________________________________________________________________________________________________________________________________________</p>
</section>
</section>
<section id="regresión-lineal-simple-y-múltiple-evaporación-de-suelo" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="regresión-lineal-simple-y-múltiple-evaporación-de-suelo"><span class="header-section-number">2</span> Regresión lineal simple y múltiple: evaporación de suelo</h2>
<section id="contexto-1" class="level4" data-number="2.0.1">
<h4 data-number="2.0.1" class="anchored" data-anchor-id="contexto-1"><span class="header-section-number">2.0.1</span> Contexto</h4>
<p>La base de datos (<em>evaporacion.txt</em>) contiene registros diarios de evaporación de suelo (agua_eva, en mm), temperatura máxima del suelo (tpsuelma, en °F) y temperatura máxima del aire (tairemax, en °F). El objetivo es construir un modelo estadístico para predecir la evaporación diaria.</p>
</section>
<section id="exploración-y-correlación" class="level4" data-number="2.0.2">
<h4 data-number="2.0.2" class="anchored" data-anchor-id="exploración-y-correlación"><span class="header-section-number">2.0.2</span> Exploración y correlación</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Carga de los datos</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>data_evap <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"datos/evaporacion.txt"</span>, <span class="at">head =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Mostrar head de la tabla</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_evap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tpsuelma tairemax agua_eva
1       84       85       30
2       84       86       34
3       79       83       33
4       81       83       26
5       84       88       41
6       74       77        4</code></pre>
</div>
</div>
<ol type="1">
<li>Cargue los datos y construya una matriz de dispersión (<em>scatterplot matrix</em>) que muestre las relaciones entre las tres variables. Incluya el gráfico. Describa en pocas líneas: ¿qué relaciones observa? ¿Parecen lineales?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Visualización de la scatterplot matrix</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(data_evap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>Los scatter plot muestran, a primera vista, que para todas las combinaciones entre variables hay una relación lineal. La misma debe posteriormente probarse a través de la evaluación de parámetros estadísticos.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="2" type="1">
<li>Calcule la matriz de correlaciones entre las tres variables. Pegue el output. Preste especial atención a la correlación entre tpsuelma y tairemax: ¿cuánto vale y qué implicancia puede tener esto al construir un modelo de regresión múltiple?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Visualización de la matriz de correlación</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data_evap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          tpsuelma  tairemax  agua_eva
tpsuelma 1.0000000 0.9268580 0.8933048
tairemax 0.9268580 1.0000000 0.8509974
agua_eva 0.8933048 0.8509974 1.0000000</code></pre>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>El coeficiente de correlación entre tpsuelma y tairemax (r = 0.9268) muestra un alto grado de relación lineal entre las variables. Construir un modelo que incluya ambas variables, puede dar como un resultado uno donde no sea distinguible el efecto individual de cada una sobre la variable dependiente.</p>
<p>________________________________________________________________________________________________________________</p>
</section>
<section id="modelo-de-regresión-múltiple" class="level4" data-number="2.0.3">
<h4 data-number="2.0.3" class="anchored" data-anchor-id="modelo-de-regresión-múltiple"><span class="header-section-number">2.0.3</span> Modelo de regresión múltiple</h4>
<ol start="3" type="1">
<li>Ajuste un modelo de regresión lineal múltiple con agua_eva como variable respuesta, y tpsuelma y tairemax como regresoras. Pegue el summary() completo.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Defino un primer modelo</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Variables predictoras: T. máxima del suelo (tpsuelma) y T. máxima del aire (tairemax)</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(agua_eva <span class="sc">~</span> tpsuelma <span class="sc">+</span> tairemax, <span class="at">data =</span> data_evap)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Summary del modelo</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = agua_eva ~ tpsuelma + tairemax, data = data_evap)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.4001  -2.1488   0.0814   3.3825  13.2875 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -169.4393    24.7330  -6.851    7e-07 ***
tpsuelma       1.8969     0.6466   2.934  0.00768 ** 
tairemax       0.4734     0.7325   0.646  0.52479    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.549 on 22 degrees of freedom
Multiple R-squared:  0.8018,    Adjusted R-squared:  0.7837 
F-statistic: 44.49 on 2 and 22 DF,  p-value: 1.859e-08</code></pre>
</div>
</div>
<p>________________________________________________________________________________________________________________</p>
<ol start="4" type="1">
<li>Indique el valor del <span class="math inline">\(R^{2}\)</span> ajustado obtenido. ¿Qué significa concretamente en el contexto de este problema? Escriba una oración que un profesional sin formación en estadística avanzada pueda entender.</li>
</ol>
<p><strong>Respuesta:</strong></p>
<p>El valor de <span class="math inline">\(R^{2}\)</span> ajustado obtenido para el modelo ajustado fue de 0.7837. Este parámetro permite medir la proporción de variabilidad de la variable respuesta que es explicada por el modelo ajustado respecto de la variabilidad total observada. En el contexto del problema en estudio, esto puede interpretarse como que aproximadamente el 78% de las variaciones observadas en la evaporación del suelo pueden ser explicadas a partir del cambio en la temperatura del suelo y la temperatura del aire mediante el modelo ajustado.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="5" type="1">
<li>Utilizando los coeficientes estimados del modelo múltiple (ítem 3): ¿Qué se espera que ocurra con la evaporación si la temperatura máxima del suelo aumenta 1°F, manteniendo constante la temperatura del aire? Use el valor exacto del coeficiente de su output para responder.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Mostrar los coeficientes del modelo ajustado </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)     tpsuelma     tairemax 
-169.4392837    1.8969411    0.4734152 </code></pre>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>El coeficiente del modelo ajustado para la temperatura máxima del suelo obtenido fue <span class="math inline">\(\beta_{tpsuelma}\)</span> = 1.8969 mm/°F. Si se mantiene la temperatura máxima del aire constante, un cambio en 1 °F de la tempratura del suelo, se va a traducir en el aumento de aproximadamente 1.90 mm en la evapotranspiración.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="6" type="1">
<li>Calcule el Factor de Inflación de la Varianza (VIF) para las variables del modelo múltiple. Pegue el output. ¿Hay indicios de multicolinealidad? ¿Qué valor o criterio utilizó para tomar esa decisión?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Cálculo del factor VIF</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tpsuelma tairemax 
7.095507 7.095507 </code></pre>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>El valor VIF para ambas variables resultó ser &gt; 5. Esto muestra tanto la temperatura del suelo como la del aire medidas presentan multicolinealidad.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="7" type="1">
<li>Ajuste dos modelos de regresión lineal simple: uno con <em>tpsuelma</em> como regresora y otro con <em>tairemax</em>. Para cada modelo indique el <span class="math inline">\(R^{2}\)</span> y compárelo con el <span class="math inline">\(R^{2}\)</span> ajustado del modelo múltiple del ítem 3. Organice los resultados en una tabla comparativa.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Defino modelo 2.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Variable predictora: T. máxima del suelo (tpsuelma)</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(agua_eva <span class="sc">~</span> tpsuelma, <span class="at">data =</span> data_evap)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Defino modelo 3</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Variable predictora: T. máxima del aire (tairemax)</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>model_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(agua_eva <span class="sc">~</span> tairemax, <span class="at">data =</span> data_evap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Summary modelo 2</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = agua_eva ~ tpsuelma, data = data_evap)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.6100  -2.4627   0.5269   2.5373  12.9585 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -160.4133    20.1522  -7.960 4.67e-08 ***
tpsuelma       2.2842     0.2396   9.532 1.87e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.465 on 23 degrees of freedom
Multiple R-squared:  0.798, Adjusted R-squared:  0.7892 
F-statistic: 90.86 on 1 and 23 DF,  p-value: 1.874e-09</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Summary modelo 3</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = agua_eva ~ tairemax, data = data_evap)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.5049  -3.4357  -0.5049   5.4258  13.3565 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -184.9817    27.8693  -6.637 9.01e-07 ***
tairemax       2.4654     0.3172   7.771 7.03e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.554 on 23 degrees of freedom
Multiple R-squared:  0.7242,    Adjusted R-squared:  0.7122 
F-statistic: 60.39 on 1 and 23 DF,  p-value: 7.03e-08</code></pre>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>En la tabla de continuación de resumen los resultados del <span class="math inline">\(R^{2}\)</span> ajustado para los tres modelos</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Modelo</th>
<th>Var. predictora</th>
<th><span class="math inline">\(R^{2}\)</span> (Ajustado)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Modelo 1</em></td>
<td>T. Máx. Suelo + T. Máx. Aire</td>
<td>0.7837</td>
</tr>
<tr class="even">
<td><em>Modelo 2</em></td>
<td>T. Máx. Suelo</td>
<td>0.7892</td>
</tr>
<tr class="odd">
<td><em>Modelo 3</em></td>
<td>T. Máx. Aire</td>
<td>0.7122</td>
</tr>
</tbody>
</table>
<p>________________________________________________________________________________________________________________</p>
<ol start="8" type="1">
<li>Considerando los resultados de los ítems 2, 3, 6 y 7 (correlación entre predictores, coeficientes estimados, multicolinealidad y bondad de ajuste): ¿cuál de los tres modelos recomendaría para predecir la evaporación? Justifique explícitamente su elección.</li>
</ol>
<p><strong>Respuesta:</strong></p>
<p>El análisis de correlación entre predictores arroja El resultado de los <span class="math inline">\(R^{2}\)</span> ajustados para los tres modelos arroja que el que utiliza la variable de temperatura máxima del suelo (<em>tpsuelma</em>), es la que tiene el coeficiente más alto. De esta forma, es el que mejor explica la variación del cambio de la evaporación del suelo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_evap<span class="sc">$</span>tpsuelma, data_evap<span class="sc">$</span>agua_eva, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"T. Máx. Suelo (°F)"</span>, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Evaporación agua (mm)"</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">coefficients</span>(model_2), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, </span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="st">"Modelo 2"</span>, </span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">"red"</span>, </span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>________________________________________________________________________________________________________________</p>
<ol start="9" type="1">
<li>Se registró un día con <em>tpsuelma</em> = 88°F y <em>tairemax</em> = 90°F. Usando los coeficientes del modelo que seleccionó en el ítem 8, prediga la evaporación esperada ese día. Muestre el cálculo explícito con los valores numéricos de su ecuación ajustada (no alcanza con pegar la salida de predict(); escriba la operación aritmética)</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Guardo los beta del modelo ajustado</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="fu">coefficients</span>(model_2)[<span class="dv">1</span>] <span class="do">## beta_0 = -160.4133 </span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="fu">coefficients</span>(model_2)[<span class="dv">2</span>] <span class="do">## beta_1 = 2.284238 </span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Defino tpsuelma</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>x_pred <span class="ot">&lt;-</span> <span class="dv">88</span> <span class="do">## tpsuelma = 88°F</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Predicción</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">&lt;-</span> beta_0 <span class="sc">+</span> beta_1<span class="sc">*</span>x_pred</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>y_pred</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   40.59969 </code></pre>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>El valor predicho para una temperatura de 88 °F fue de 40.6 mm.</p>
<p>________________________________________________________________________________________________________________</p>
</section>
<section id="diagnóstico-del-modelo" class="level4" data-number="2.0.4">
<h4 data-number="2.0.4" class="anchored" data-anchor-id="diagnóstico-del-modelo"><span class="header-section-number">2.0.4</span> Diagnóstico del modelo</h4>
<ol start="10" type="1">
<li>Para el modelo seleccionado, incluya:</li>
</ol>
<!-- -->
<ol type="a">
<li>El gráfico de residuos vs.&nbsp;valores ajustados.</li>
<li>Una evaluación escrita: ¿se observa algún patrón sistemático en los residuos? ¿Considera que el supuesto de homocedasticidad se cumple? Fundamente su respuesta en funcion de lo que muestra el gráfico.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Ploteo gráfico de residuos estandarizados vs. valores ajustados</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted.values</span>(model_2), <span class="fu">rstandard</span>(model_2),</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Valores ajustados"</span>, <span class="at">ylab =</span> <span class="st">"Residuos estandarizados"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TrabajoFinalEstd-Barrionuevo_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Respuesta:</strong></p>
<p>A partir del gráfico de residuos estandarizados vs.&nbsp;valores ajustados, no se observa que los residuos sigan un patrón definido. Es decir, a lo largo del eje de valores predichos, los residuos se distribuyen de manera aproximadamente homogénea alrededor de 0, principalmente entre -2 y 2. En función de esto, es posible decir que se cumple el supuesto de homocedasticidad.</p>
<p>________________________________________________________________________________________________________________</p>
<ol start="11" type="1">
<li>Un estudiante observa que el modelo múltiple (ítem 3) tiene un <span class="math inline">\(R^{2}\)</span> mayor que cualquiera de los dos modelos simples, y concluye que “siempre es mejor incluir más variables porque el <span class="math inline">\(R^{2}\)</span> solo puede aumentar o mantenerse igual”. ¿Está de acuerdo con esta afirmación? Desarrolle su respuesta considerando al menos dos argumentos estadísticos concretos.</li>
</ol>
<p>No es correcto afirmar que, al incluir más variables predictoras en el ajuste de un modelo, el <span class="math inline">\(R^{2}\)</span> ajustado necesariamente aumenta o se mantiene constante. Esto es lo que se observó para el caso del modelo ajustado para la evaporación del agua en función de las temperaturas del suelo y del aire. En este caso, al incluir ambas variables predictoras, la bondad de ajuste del modelo resulta menor que al incluir solo una de ellas. Esto se debe a que agregar información redundante, producto de la alta multicolinealidad entre las variables predictoras, incrementa la complejidad del modelo sin mejorar su capacidad explicativa.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>